package com.serrano.academically.utils

object Routes {

    const val SPLASH = "Splash"
    const val MAIN = "Main"
    const val ABOUT = "About"
    const val SIGNUP = "Signup"
    const val LOGIN = "Login"
    const val ASSESSMENT = "Assessment"
    const val CHOOSE_ASSESSMENT = "ChooseAssessment"
    const val ASSESSMENT_OPTION = "AssessmentOption"
    const val ASSESSMENT_RESULT = "AssessmentResult"
    const val DASHBOARD = "Dashboard"
    const val COURSES_MENU = "CoursesMenu"
    const val FIND_TUTOR = "FindTutor"
    const val NOTIFICATIONS = "Notifications"
    const val PROFILE = "Profile"
    const val LEADERBOARD = "Leaderboard"
    const val ANALYTICS = "Analytics"
    const val MESSAGE_TUTOR = "MessageTutor"
    const val CREATE_SESSION = "CreateSession"
    const val EDIT_SESSION = "EditSession"
    const val ABOUT_SESSION = "AboutSession"
    const val ABOUT_STUDENT = "AboutStudent"
    const val ABOUT_TUTOR = "AboutTutor"
    const val ACCOUNT = "Account"
    const val ACHIEVEMENTS = "Achievements"
    const val ASSIGNMENT_OPTION = "AssignmentOption"
    const val CREATE_ASSIGNMENT = "CreateAssignment"
    const val ASSIGNMENT = "Assignment"
    const val ARCHIVE = "Archive"
    const val PATTERN_ASSESSMENT = "PatternAssessment"
    const val SUPPORT = "Support"
    const val SUPPORT_CHAT = "SupportChat"

}