package com.serrano.academically.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF039BE5)
val md_theme_light_onPrimary = Color(0xFF141414)
val md_theme_light_primaryContainer = Color(0xFF64B5F6)
val md_theme_light_onPrimaryContainer = Color(0xFFFFFFFF)
val md_theme_light_secondary = Color(0xFFFFEB3B)
val md_theme_light_onSecondary = Color(0xFF141414)
val md_theme_light_secondaryContainer = Color(0xFF2E7D32)
val md_theme_light_onSecondaryContainer = Color(0xFFFFFFFF)
val md_theme_light_tertiary = Color(0xFFFFFFCC)
val md_theme_light_onTertiary = Color(0xFF141414)
val md_theme_light_tertiaryContainer = Color(0xFF512DA8)
val md_theme_light_onTertiaryContainer = Color(0xFFFFFFFF)
val md_theme_light_surface = Color(0xFF4CAF50)
val md_theme_light_onSurface = Color(0xFFFFFFFF)
val md_theme_light_surfaceVariant = Color(0xFF00BCD4)
val md_theme_light_onSurfaceVariant = Color(0xFF141414)
val md_theme_light_error = Color(0xFFE53935)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_background = Color(0xFF000000)
val md_theme_light_onBackground = Color(0xFFFFFFFF)

val md_theme_dark_primary = Color(0xFF01579B)
val md_theme_dark_onPrimary = Color(0xFF141414)
val md_theme_dark_primaryContainer = Color(0xFF1976D2)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFFFFF)
val md_theme_dark_secondary = Color(0xFF827717)
val md_theme_dark_onSecondary = Color(0xFF141414)
val md_theme_dark_secondaryContainer = Color(0xFF1B5E20)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFFFFF)
val md_theme_dark_tertiary = Color(0xFFD4E157)
val md_theme_dark_onTertiary = Color(0xFF141414)
val md_theme_dark_tertiaryContainer = Color(0xFF311B92)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFFFFF)
val md_theme_dark_surface = Color(0xFF1B5E20)
val md_theme_dark_onSurface = Color(0xFFFFFFFF)
val md_theme_dark_surfaceVariant = Color(0xFF004D40)
val md_theme_dark_onSurfaceVariant = Color(0xFF141414)
val md_theme_dark_error = Color(0xFFB71C1C)
val md_theme_dark_onError = Color(0xFFFFFFFF)
val md_theme_dark_background = Color(0xFF000000)
val md_theme_dark_onBackground = Color(0xFFFFFFFF)