package com.serrano.academically.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF2196F3)
val md_theme_light_onPrimary = Color(0xFF000000)
val md_theme_light_primaryContainer = Color(0xFF90CAF9)
val md_theme_light_onPrimaryContainer = Color(0xFF1565C0)
val md_theme_light_secondary = Color(0xFFFFEB3B)
val md_theme_light_onSecondary = Color(0xFF000000)
val md_theme_light_secondaryContainer = Color(0xFFFFF59D)
val md_theme_light_onSecondaryContainer = Color(0xFFF9A825)
val md_theme_light_tertiary = Color(0xFFFFFFCC)
val md_theme_light_onTertiary = Color(0xFF141414)
val md_theme_light_tertiaryContainer = Color(0xFFFFFFE6)
val md_theme_light_onTertiaryContainer = Color(0xFFFFFF80)
val md_theme_light_surface = Color(0xFF4CAF50)
val md_theme_light_onSurface = Color(0xFFFFFFFF)
val md_theme_light_surfaceVariant = Color(0xFF00BCD4)
val md_theme_light_onSurfaceVariant = Color(0xFFB2EBF2)

val md_theme_dark_primary = Color(0xFF64B5F6)
val md_theme_dark_onPrimary = Color(0xFFFFFFFF)
val md_theme_dark_primaryContainer = Color(0xFF0D47A1)
val md_theme_dark_onPrimaryContainer = Color(0xFFBBDEFB)
val md_theme_dark_secondary = Color(0xFFFFF176)
val md_theme_dark_onSecondary = Color(0xFFFFFFFF)
val md_theme_dark_secondaryContainer = Color(0xFFF57F17)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFF9C4)
val md_theme_dark_tertiary = Color(0xFFFFFF90)
val md_theme_dark_onTertiary = Color(0xFFFFFFFF)
val md_theme_dark_tertiaryContainer = Color(0xFFFFFF66)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFFFB3)
val md_theme_dark_surface = Color(0xFF388E3C)
val md_theme_dark_onSurface = Color(0xFF000000)
val md_theme_dark_surfaceVariant = Color(0xFF4DD0E1)
val md_theme_dark_onSurfaceVariant = Color(0xFF006064)